"""Initial migration

Revision ID: 93fe4be09ee6
Revises: 
Create Date: 2024-01-07 19:13:37.418240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93fe4be09ee6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('codigo_interno', sa.String(), nullable=True),
    sa.Column('codigo_local', sa.String(), nullable=True),
    sa.Column('codigo_atacado', sa.String(), nullable=True),
    sa.Column('codigo_do_preco', sa.String(), nullable=True),
    sa.Column('grupo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
